#-------------------------------
# General Site Settings
title: Lumunix
logo: '/images/hi.png' # You can add own logo. For example '/images/logo.png'.
description: Lumunix Blog
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://lumunix.github.io/" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Lumunix
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title:
  description:
  image:


#-------------------------------
# Contact Settings
contact:
  email: lumunix@icloud.com # Add your email for contact form
  description:  # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "logo-twitter", link: "https://twitter.com/Lumunix"}
- {icon: "logo-instagram", link: "https://www.instagram.com/lum_unix/?hl=en"}
- {icon: "logo-youtube", link: "https://www.youtube.com/channel/UClirzTkXbUFGsfP8aiUqOGg"}
- {icon: "logo-github", link: "https://lumunix.github.io/"}
- {icon: "logo-discord", link: "https://discord.gg/S44eGxVNzT"}
- {icon: "logo-twitch", link: "https://www.twitch.tv/lumunix"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: lumunix # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-J7RRTGG6TL # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
