version: '3'
services:
  site:
    environment:
      JEKYLL_ENV: development
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: >
      jekyll serve \
        --watch \
        --force_polling \
        --host 0.0.0.0 \
        --port 4000 \
